CREATE TABLE IF NOT EXISTS participant (
    id SERIAL PRIMARY KEY,
    full_name VARCHAR NOT NULL,
    linkedin VARCHAR
);
CREATE TABLE IF NOT EXISTS project_type (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS season (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS it_field (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS role (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL
);